name: Extension Test On Relationship
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  meshery-extensions-test-relationship:
    uses: ./.github/workflows/extension-test-reusable.yml
    secrets: inherit
    with:
      checkout_ref: "master"
      test_command: "make test-relationship"

  update-meshery-test-relationship-report:
    name: Update meshery test relationship report
    needs: [meshery-extensions-test-relationship]
    runs-on: ubuntu-24.04
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: relationship-playwright-report
        path: meshery-extensions/meshmap/

    - name: Rename file version with underscore
      run: |
        for file in meshery-extensions/meshmap/relationship-*.json; do
          new_file=$(echo "$file" | sed 's/\./_/g' | sed 's/_json/.json/')
          mv "$file" "$new_file"
        done

    - name: Check out Meshery code
      uses: actions/checkout@v5
      with:
        repository: meshery/meshery
        token: ${{ secrets.GH_ACCESS_TOKEN }} 
        fetch-depth: 1
        path: meshery

    - name: Create target directory if not exist
      run: mkdir -p meshery/docs/_data/relationshiptestresult

    - name: Move relationship.json to docs/_data folder
      run: mv meshery-extensions/meshmap/relationship-*.json meshery/docs/_data/relationshiptestresult/
      
    - name: Display structure of downloaded files
      run: ls -R meshery/docs/_data/relationshiptestresult

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Updated relationship test result"
        branch: master
        repository: meshery
        commit_options: "--signoff"
        file_pattern: 'docs/_data/relationshiptestresult/relationship-*.json'
        commit_user_name: l5io
        commit_user_email: ci@layer5.io
        commit_author: 'l5io <l5io@users.noreply.github.com>'
